2023-10-23 11:25:23 | INFO    | __main__:stash:125 | run - {'role': 'EpicPlayer', 'headless': True}
2023-10-23 11:25:30 | INFO    | __main__:claim_epic_games:91 | Try to flush cookie - {'task': 'claim_epic_games'}
2023-10-23 11:25:35 | INFO    | epic_games.agent:_login:187 | login-with-email - {'url': 'https://www.epicgames.com/id/login?lang=en-US&noHostRedirect=true&redirectUrl=https://store.epicgames.com/en-US/free-games'}
2023-10-23 11:25:40 | DEBUG    | epic_games.agent:insert_challenge:165 | Attack challenge - {'stage': 'email_exists_prod'}
2023-10-23 11:25:41 | DEBUG    | hcaptcha_challenger.agents.playwright.control:_match_solution:377 | match model - {'resnet': 'electronic_device2316.onnx', 'prompt': 'Please click each image containing an electronic device'}
2023-10-23 11:25:47 | DEBUG    | epic_games.agent:insert_challenge:168 | Parse result - {'stage': 'email_exists_prod', 'result': 'success'}
2023-10-23 11:25:54 | DEBUG    | epic_games.agent:insert_challenge:159 | Attack challenge - {'stage': 'login_prod'}
2023-10-23 11:25:54 | DEBUG    | hcaptcha_challenger.agents.playwright.control:_match_solution:377 | match model - {'resnet': 'smartwatch2309.onnx', 'prompt': 'Please click each image containing a smаrtwatсh'}
2023-10-23 11:25:58 | DEBUG    | epic_games.agent:insert_challenge:168 | Parse result - {'stage': 'login_prod', 'result': 'retry'}
2023-10-23 11:26:03 | DEBUG    | hcaptcha_challenger.agents.playwright.control:_match_solution:377 | match model - {'resnet': 'electronic_device2316.onnx', 'prompt': 'Please click each image containing an electronic ԁеvісe'}
2023-10-23 11:26:15 | DEBUG    | epic_games.agent:insert_challenge:168 | Parse result - {'stage': 'login_prod', 'result': 'success'}
2023-10-23 11:26:45 | SUCCESS    | epic_games.agent:_login:203 | login - {'result': 'Successfully refreshed tokens'}
2023-10-23 11:26:57 | SUCCESS    | epic_games.agent:flush_token:224 | flush_token - {'path': PosixPath('/home/runner/work/auto-game/auto-game/epic/user_data_dir/epic-games@3356036505/ctx_cookie.json')}
2023-10-23 11:26:57 | WARNING    | epic_games.agent:get_order_history:389 | Failed to get order history, cookie may have expired - {}
2023-10-23 11:26:58 | DEBUG    | __main__:create_tasks:60 | Put task - {'title': 'The Evil Within', 'url': 'https://store.epicgames.com/en-US/p/the-evil-within'}
2023-10-23 11:26:58 | DEBUG    | __main__:create_tasks:60 | Put task - {'title': 'Eternal Threads', 'url': 'https://store.epicgames.com/en-US/p/eternal-threads-197169'}
2023-10-23 11:26:58 | INFO    | epic_games.agent:claim_weekly_games:232 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/the-evil-within'}
2023-10-23 11:27:35 | INFO    | epic_games.agent:claim_weekly_games:232 | claim_weekly_games - {'action': 'go to store', 'url': 'https://store.epicgames.com/en-US/p/eternal-threads-197169'}
2023-10-23 11:27:47 | ERROR    | __main__:run:144 | An error has been caught in function 'run', process 'MainProcess' (3663), thread 'MainThread' (139651491253120): - {}
Traceback (most recent call last):
  File "/home/runner/work/auto-game/auto-game/epic/src/claim.py", line 148, in <module>
    asyncio.run(run())
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 636, in run_until_complete
    self.run_forever()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    self._run_once()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    handle._run()
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
> File "/home/runner/work/auto-game/auto-game/epic/src/claim.py", line 144, in run
    await agent.stash()
  File "/home/runner/work/auto-game/auto-game/epic/src/claim.py", line 137, in stash
    await self.claim_epic_games(context)
  File "/home/runner/work/auto-game/auto-game/epic/src/claim.py", line 116, in claim_epic_games
    await epic.claim_weekly_games(page, single_promotions)
  File "/home/runner/work/auto-game/auto-game/epic/src/epic_games/agent.py", line 248, in claim_weekly_games
    await expect(cta_btn).to_have_text("View In Cart")
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/async_api/_generated.py", line 20080, in to_have_text
    await self._impl_obj.to_have_text(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_assertions.py", line 455, in to_have_text
    await self._expect_impl(
  File "/opt/hostedtoolcache/Python/3.10.13/x64/lib/python3.10/site-packages/playwright/_impl/_assertions.py", line 70, in _expect_impl
    raise AssertionError(f"{out_message}\nActual value: {actual} {log}")
AssertionError: Locator expected to have text 'View In Cart'
Actual value: None 
Call log:
LocatorAssertions.to_have_text with timeout 5000ms
waiting for locator("xpath=//aside//button[@data-testid='add-to-cart-cta-button']")
